kind: Service
apiVersion: v1
metadata:
  name: public-service
  labels:
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: nginx
  #  role: green   #Specify role to point to green or blue, otherwise it becomes a canary setup where trafic is routed 50/50 to green and blue deployment
    
  ports:
    - port: 80
      targetPort: 80
